### ISSUE TITLE
'Routing' page issue

### ISSUE THREAD

**Issue by lechner** [dart-lang/site-angulardart#131]
From URL: https://angulardart.dev/tutorial/toh-pt5

I am still learning Dart. I had to replace the line in `main.dart`
```
import 'package:angular_tour_of_heroes/app_component.template.dart' as ng;
```
with the line
```
import 'package:angular_app/app_component.template.dart' as ng;
```
I also made a similar adjustment in `test/app_test.dart`.

Kind regards
Felix Lechner

**Comment by chalin** [comment]
Hi. Thanks for filing an issue. That likely because you missed the following step when you created the project (https://angulardart.dev/tutorial/toh-pt0#create-the-app):

> ## Create the app
>
> Let’s get started. Create a project named `angular_tour_of_heroes`, ...
