### ISSUE TITLE
Please tell me how to fix the error?

### ISSUE THREAD

**Issue by MitaiGit** [dart-lang/site-angulardart#132]
Exception: Server error; cause: Expected a value of type 'int', but got one of type 'String'
`import 'dart:convert';
import 'package:http/http.dart';

import 'advert.dart';

class AdvertService {
  static final _headers = {'Content-Type': 'application/json'};
  static const _advertsUrl = 'http://127.0.0.1:8000/adverts/';
  final Client _http;

  AdvertService(this._http);

  Future<List<Advert>> getAll() async {
    try {
      final response = await _http.get(_advertsUrl);
      final adverts = (_extractData(response) as List)
        .map((value) => Advert.fromJson(value))
        .toList();
      return adverts;
    } catch (e) {
      throw _handleError(e);
    }
  }

  Future<Advert> create(String title) async {
    try {
      final response = await _http.post(_advertsUrl,
          headers: _headers, body: json.encode({'title': title}));
      return Advert.fromJson(_extractData(response));
    } catch (e) {
      throw _handleError(e);
    }
  }

  dynamic _extractData(Response resp) => json.decode(resp.body)['data'];

  Exception _handleError(dynamic e) {
    print(e); // for demo purposes only
    return Exception('Server error; cause: $e');
  }
}`

`class Advert {
  final int id;
  String title, owner, description, date;

  Advert(this.id, this.title, this.owner, this.description, this.date);

  factory Advert.fromJson(Map<String, dynamic> advert) =>
      Advert(_toInt(advert['id']), advert['title'], advert['owner'],
        advert['description'], advert['date']);

  Map toJson() => {'id': id, 'title': title, 'owner': owner,
    'description': description, 'date': date};
}

int _toInt(id) => id is int ? id : int.parse(id);`

when will the new angulardart tutorial be available?

**Comment by MitaiGit** [comment]
int _toInt(id) => id is int ? id : int.parse(id);
here is this line, it is in the source code but not in the tutorial, the problem is in it right?

**Comment by MitaiGit** [comment]
![Снимок экрана от 2020-02-09 11-44-57](https://user-images.githubusercontent.com/32243762/74097739-a449c480-4b31-11ea-8fcf-d679d245ec6a.png)
terminal pycharm tell my it is ok
[09/Feb/2020 11:45:48] "GET /adverts/ HTTP/1.1" 200 492

**Comment by MitaiGit** [comment]
I removed my code, made it your way from the tutorial, the result is unchanged
![Снимок экрана от 2020-02-10 15-52-52](https://user-images.githubusercontent.com/32243762/74144787-34196c80-4c1f-11ea-8d87-fb763ff5a3a6.png)

**Comment by MitaiGit** [comment]
`class Hero {
  final int id;
  String name;

  Hero(this.id, this.name);

  factory Hero.fromJson(Map<String, dynamic> hero) =>
      Hero(_toInt(hero['id']), hero['name']);

  Map toJson() => {'id': id, 'name': name};
}

int _toInt(id) => id is int ? id : int.parse(id);`

**Comment by MitaiGit** [comment]
json in browser look at
[{"id":1,"name":"Fox"},{"id":2,"name":"Petr"},{"id":3,"name":"Вебшторм"},{"id":4,"name":"Kamaz"},{"id":5,"name":"Beer"},{"id":6,"name":"акуленок ту-ру-ру-ру"}]

**Comment by MitaiGit** [comment]
![Снимок экрана от 2020-02-10 20-41-47](https://user-images.githubusercontent.com/32243762/74164835-1e6b6d80-4c46-11ea-86ed-ba37bd858ca1.png)

**Comment by MitaiGit** [comment]
class Hero {
  final int id;
  String name;

  Hero(this.id, this.name);

  factory Hero.fromJson(Map<String, dynamic> hero) =>
      Hero(_toInt(hero['id']), hero['name']);

  Map toJson() => {'id': id, 'name': name};
}

int _toInt(id) => id is int ? id : int.parse(id);

import 'package:http/http.dart';

import 'hero.dart';

class HeroService {
  static final _headers = {'Content-Type': 'application/json'};
  static const _heroesUrl = 'http://127.0.0.1:8000/heroes'; // URL to web API
  final Client _http;

  HeroService(this._http);

  Future<List<Hero>> getAll() async {
    try {
      final response = await _http.get(_heroesUrl);
      final heroes = (_extractData(response) as List)
          .map((value) => Hero.fromJson(value))
          .toList();
      return heroes;
    } catch (e) {
      throw _handleError(e);
    }
  }

  Future<Hero> create(String name) async {
    try {
      final response = await _http.post(_heroesUrl,
          headers: _headers, body: json.encode({'name': name}));
      return Hero.fromJson(_extractData(response));
    } catch (e) {
      throw _handleError(e);
    }
  }

  dynamic _extractData(Response resp) => json.decode(resp.body)['data'];

  Exception _handleError(dynamic e) {
    print(e); // for demo purposes only
    return Exception('Server error; cause: $e');
  }
}
Exception: Server error; cause: Expected a value of type 'int', but got one of type 'String'

**Comment by MitaiGit** [comment]
why the error? the code is exactly like in the tutorial and there are no additional fields...
above there is a web storm screen where it gets data from Django why doesn't angulardart get it?

**Comment by kwalrath** [comment]
Have you tried using an older version of the Dart SDK?

**Comment by MitaiGit** [comment]
> Вы пытались использовать старую версию Dart SDK?

no, I haven't tried it, the tutorial code doesn't match the new SDK version? my installed version 2.7.1 according to the instructions https://dart.dev/get-dart for debian via apt

**Comment by kwalrath** [comment]
The SDK version was just a guess. It looks like [tests are passing with 2.7.0](https://travis-ci.org/dart-lang/site-angulardart), but some tests are skipped (as you can see from the `skip` lines in https://github.com/dart-lang/site-angulardart/blob/master/.travis.yml).

Unfortunately, we don't have the resources to devote to AngularDart outside of Google (where it's most heavily used, but with different tooling). https://github.com/dart-lang/angular/issues/1866#issuecomment-571851626 has more information about our internal focus.

That said... We welcome solutions and PRs. I wish I could do more to help you.

**Comment by MitaiGit** [comment]
managed to get data from the heroes file.json the difference is that there is such a string
`{
  **"data":** [
    { "id": "1", "name": "Windstorm" },
    { "id": "2", "name": "Bombasto" },
    { "id": "3", "name": "Magneta" },
    { "id": "4", "name": "Tornado" }
  ]
}`
my json derivable
`[{"id":1,"name":"Windstorm"},{"id":2,"name":"Bombasto"},{"id":3,"name":"Magneta"},{"id":4,"name":"Tornado"}]` no 'data':

**Comment by kwalrath** [comment]
Oh interesting! I wonder when that changed, and what changes we'd need to make or version(s) we'd need to pin to for "correct" results.

**Comment by MitaiGit** [comment]
I don't have json this -> data: and to get the data you need from the string -> dynamic _extractData (Response resp) => json.decode (resp.body) ['data']; delete ['data'] or edit JSON generation django_rest.
Thunks you kwalrath

**Comment by MitaiGit** [comment]
> Ох, интересно! Интересно, когда это изменится, и какие изменения нам нужно будет сделать, или версии (версиях), к которым нам нужно будет прикрепиться, чтобы получить «правильные» результаты.

this is due to security, json must come from the server with the "data":  key
Ideally, you need new documentation, which is the first thing that catches your eye when reading this version of the tutorial? framwork for creating sites, does not talk about images, how to display them, make thumbnails, nothing at all, this is strange, and the documentation should not be dead, if 10 people asked the same question, it is more logical to tell this point in detail in the documentation, it should be alive and updated

**Comment by MitaiGit** [comment]
This is a lot of work, and it should be paid, and I can't say that Google has a person who has the position of "documentation writer", good documentation eliminates 90% of questions

**Comment by MitaiGit** [comment]
I don't know how to get data from such a json
`{
    "data": [
        {
            "type": "Hero",
            "id": "1",
            "attributes": {
                "name": "Windstorm"
            }
        },
        {
            "type": "Hero",
            "id": "2",
            "attributes": {
                "name": "Bombasto"
            }
        },
        {
            "type": "Hero",
            "id": "3",
            "attributes": {
                "name": "Magneta"
            }
        },
        {
            "type": "Hero",
            "id": "4",
            "attributes": {
                "name": "Tornado"
            }
        }
    ]
}`

**Comment by MitaiGit** [comment]
`class Hero {
  final int id;
  String name;

  Hero(this.id, this.name);

  factory Hero.fromJson(Map<String, dynamic> hero) =>
      Hero(_toInt(hero['id']), hero['attributes']['name']);

  Map toJson() => {'id': id, 'name': name};
}

int _toInt(id) => id is int ? id : int.parse(id);`
