### ISSUE TITLE
Autopush isn't working

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-angulardart#30]
I expected my changes from #29 to be auto-deployed, but they weren't.

**Comment by mit-mit** [comment]
Looks like the build is failing: https://travis-ci.com/dart-lang/site-angulardart

**Comment by kwalrath** [comment]
Seems like it might be flake. I've restarted the build.

**Comment by mit-mit** [comment]
Actually, it looks like dartfmt want to format one of the files a bit differently in Dart 2.3

**Comment by mit-mit** [comment]
Ah, you fixed. thanks!
