### ISSUE TITLE
Code snippet broken in dependency injection guide

### ISSUE THREAD

**Issue by polybuildr** [dart-lang/site-angulardart#32]
In https://angulardart.dev/guide/dependency-injection#angular-dependency-injection, the code snippet below "Start by reviewing this simplified version of the heroes feature from the The Tour of Heroes." seems to be broken.

**Comment by polybuildr** [comment]
Also in the section https://angulardart.dev/guide/dependency-injection#inject-a-service
after the sentence "Here’s the revised component, making use of the injected service, side-by-side with the previous version for comparison."

**Comment by polybuildr** [comment]
Sorry for the many comments, I just found that another section (and I think this is the last on this page) also has a similar issue: https://angulardart.dev/guide/dependency-injection#when-a-service-needs-a-service

**Comment by kwalrath** [comment]
Thanks very much for letting us know about these, @polybuildr.
