### ISSUE TITLE
Code snippet broken in Component testing

### ISSUE THREAD

**Issue by ChicoLin** [dart-lang/site-angulardart#35]
Code below the section below is broken.

https://angulardart.dev/guide/testing/component/input-and-output#template-syntaxtestsizer_testdart-output-after-inc

**Comment by kwalrath** [comment]
This sounds like something I should've fixed in #33.

**Comment by ChicoLin** [comment]
It doesn't seem to be fixed..

**Comment by kwalrath** [comment]
It'll take up to an hour to refresh. Could you check again then? Thanks!

**Comment by ChicoLin** [comment]
Seems it's fixed now. Thanks!
