### ISSUE TITLE
Code block broken in tutorial/toh-pt5#update-the-pubspec

### ISSUE THREAD

**Issue by NatoBoram** [dart-lang/site-angulardart#38]
https://angulardart.dev/tutorial/toh-pt5#update-the-pubspec

![image](https://user-images.githubusercontent.com/10495562/57962977-d05e4f00-78eb-11e9-9792-edb1e2d624fa.png)

**Comment by kwalrath** [comment]
Diff formatting is broken, in general. Also visible in the [codelab](https://angulardart.dev/codelabs/angular_components/2-starteasy#--depend-on-angular_components).

**Comment by kwalrath** [comment]
Looks like it's working now.

![image](https://user-images.githubusercontent.com/2164483/92541260-5b0e4000-f1fa-11ea-96ec-619cc37539c8.png)
