### ISSUE TITLE
404 on 'Search Dart Sites' page issue

### ISSUE THREAD

**Issue by raviprak** [dart-lang/site-angulardart#44]
From URL: https://angulardart.dev/search
Repro steps:
1.  Go to https://angulardart.dev/
2. In the search bar type "runApp"
3. The first search result is (click on it):
runApp function - angular library - Dart API
https://webdev.dartlang.org/api/angular/angular/runApp
4. Welcome to a 404 page

**Comment by raviprak** [comment]
I'm guessing the URL should have been https://angulardart.dev/api/angular/angular/runApp

**Comment by kwalrath** [comment]
It’s working for me now, presumably due to https://github.com/dart-lang/site-webdev/pull/1936.
