### ISSUE TITLE
Remove the tutorial from the site

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/site-angulardart#45]
The tutorial is very much out of date. Both the Angular eng team and the pkg:build team are fielding issues due to examples no longer working.

Until we are able to keep the examples up to date, we should just drop the tutorial.

**Comment by kwalrath** [comment]
Related: https://github.com/dart-lang/angular/issues/1833

**Comment by hpoit** [comment]
Thank you @alorenzen, I was just about to ask why is TOH under https://angulardart.dev/tutorial/, was not written by an AngularDart member, and is not being maintained by one either. I wouldn't however remove it completely, because it shows what AngularDart can do, and how, and it serves to me at least, as a reference.

**Comment by hpoit** [comment]
https://www.youtube.com/watch?time_continue=1240&v=PLHln7wHgPE is brilliant. I wish there was a very clear explanation of it under https://dartlang.org.

**Comment by kwalrath** [comment]
@johnpryan is going to take a quick look to see if he can easily update the tutorial.

**Comment by hpoit** [comment]
Thank you, Kathy! I now have the problem of knowing about the BLoC design pattern and knowing that it's very correct for the solution I'm building (web ERP connected to mobile apps, and web). Many are also taking notice of BLoC. Is there any chance of a tutorial for BLoC under dart.dev/ coming up soon? Just a very simple tutorial of a list of heroes? I found tutorials branching off of Paolo Soares' video, but who knows if these tutorials are in idiomatic Dart? That's my worry.
