### ISSUE TITLE
Don't use xvfb

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-angulardart#48]
See dart-lang/angular#1850

I have a vague memory of us removing xvfb from the Travis jobs of one of our sites, but it's still present in this repo: [/tool/browser.sh](https://github.com/dart-lang/site-angulardart/blob/master/tool/browser.sh).

**Comment by chalin** [comment]
Related: #86

**Comment by chalin** [comment]
We were running tests using headless chrome until an issue arose (I think that tests were timing out), so we fell back to what we were doing before. Anyhow, this has been fixed by #96.
